[package]
name = "revm_era"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

revm = { path = "../revm/crates/revm" }
era_test_node = { path = "../era-test-node"}
zksync_basic_types = {path = "../zksync-era/core/lib/basic_types"}
zksync_types = {path = "../zksync-era/core/lib/types"}
ethabi = "18.0.0"
zk_evm = {git = "https://github.com/matter-labs/era-zk_evm.git", branch = "v1.3.3"}
