[package]
name = "era_revm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#revm = { path = "../revm/crates/revm" }
revm = { git = "https://github.com/mm-zk/revm.git", branch = "release_v25_with_old_sha" }
#revm = { version = "2.3", default-features = false, features = [
#  "std",
#  "k256",
#  "with-serde",
#  "memory_limit",
#  "optional_eip3607"
#] }

# era_test_node = { path = "../era-test-node"}
era_test_node = {git = "https://github.com/matter-labs/era-test-node.git", rev = "8013425569340833d4177526850fb517c604bc49"}

# zksync_basic_types = {path = "../zksync-era/core/lib/basic_types"}
zksync_basic_types = { git = "https://github.com/matter-labs/zksync-era.git", rev = "a98e454221da7d6ecad9b317cf44b0786e819659" }

#zksync_types = {path = "../zksync-era/core/lib/types"}
zksync_types = { git = "https://github.com/matter-labs/zksync-era.git", rev = "a98e454221da7d6ecad9b317cf44b0786e819659" }
vm = { git = "https://github.com/matter-labs/zksync-era.git", rev = "a98e454221da7d6ecad9b317cf44b0786e819659" }
zksync_utils = { git = "https://github.com/matter-labs/zksync-era.git", rev = "a98e454221da7d6ecad9b317cf44b0786e819659" }


ethabi = "18.0.0"
zk_evm = {git = "https://github.com/matter-labs/era-zk_evm.git", branch = "v1.3.3"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
eyre = "0.6"